# Generated by Django 4.0.6 on 2022-07-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='role_type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role_type',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
